#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
sed -i 's/listen [::]:80 default_server;/listen 80 default_server;\nlisten [::]:80 default_server;/' /etc/nginx/sites-available/default
service nginx restart
