#!/usr/bin/env bash
# SSH client configuration

Host *
     PosswordAuthentication no 
     IdentityFile ~/.ssh/school
     SendEnv LANG LC_*
     HashKnowoHosts yes
     GSSPILAuthentication yes 
     GSSAPIDelegateCredentials no
